CREATE TABLE Teams 
( TeamId INT IDENTITY PRIMARY KEY NOT NULL,
TeamName NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE Players
( PlayerId INT IDENTITY PRIMARY KEY NOT NULL,
 PlayerName NVARCHAR(50) NOT NULL,
 Picture NVARCHAR(250) NOT NULL,
 TeamId INT NOT NULL REFERENCES dbo.Teams(TeamId)
 )